Repository TradePortProject/tradeport-frontend, pull requests merged in 2025-05, with the labels that each got.

#60 [Snyk] Upgrade axios from 1.8.3 to 1.8.4
  package-lock.json
  package.json
Labels: snyk, security

#66 [Snyk] Upgrade react-hook-form from 7.54.2 to 7.55.0
  package-lock.json
  package.json
Labels: snyk, security

#59 [Snyk] Upgrade react-router-dom from 7.3.0 to 7.4.0
  package-lock.json
  package.json
Labels: snyk, security

#81 Feature/scrum 156 dast fix
  .github/workflows/ci-dast.yml
Labels: enhancement, cicd

#82 SCRUM-158-Updated CD only on push to main
  .github/workflows/cd.yml
Labels: enhancement

#83 Feature/scrum 156 sca sast dast refactor
  .github/workflows/cd-digitalocean.yml
  .github/workflows/cd.yml
  .github/workflows/ci-dast.yml
  .github/workflows/ci-security-owasp.yml
  .github/workflows/ci-selenium.yml
  .github/workflows/ci.yml
Labels: enhancement, frontend, cicd

#84 SCRUM-156-Ci-linked-with-CD
  .github/workflows/cd.yml
Labels: documentation, frontend, cicd

#85 SCRUM-156-Ci-linked-with-CD
  .github/workflows/cd.yml
Labels: enhancement, frontend, cicd

#87 SCRUM-156-Renaming CD Dockerhub to CI
  .github/workflows/cd.yml
Labels: frontend, cicd

#88 Product-Category-Update
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  .vs/tradeport-frontend/CopilotIndices/17.13.431.34963/CodeChunks.db
  .vs/tradeport-frontend/CopilotIndices/17.13.431.34963/CodeChunks.db-shm
  .vs/tradeport-frontend/CopilotIndices/17.13.431.34963/CodeChunks.db-wal
  .vs/tradeport-frontend/CopilotIndices/17.13.431.34963/SemanticSymbols.db
  .vs/tradeport-frontend/CopilotIndices/17.13.431.34963/SemanticSymbols.db-shm
  .vs/tradeport-frontend/CopilotIndices/17.13.431.34963/SemanticSymbols.db-wal
  .vs/tradeport-frontend/FileContentIndex/9dbd4de4-9d44-41c7-9806-3356e27a7441.vsidx
  .vs/tradeport-frontend/v17/.wsuo
  .vs/tradeport-frontend/v17/DocumentLayout.json
  src/components/CatalogGrid.tsx
  src/pages/Product.tsx
Labels: frontend

#89 Update RegisterForm.tsx
  src/pages/RegisterForm.tsx
Labels: enhancement, frontend, dependabot, security, codeql

#90 SCRUM-18-fix: Update the logout comments
  README.md
Labels: documentation, enhancement, frontend

#91 SCRUM-72-Fix: Demo Purposes
  README.md
Labels: documentation

#95 [Snyk] Upgrade @reduxjs/toolkit from 2.6.1 to 2.7.0
  package-lock.json
  package.json
Labels: snyk, security

#94 [Snyk] Upgrade react-hook-form from 7.55.0 to 7.56.0
  package-lock.json
  package.json
Labels: snyk, security

#93 [Snyk] Upgrade @headlessui/react from 2.2.0 to 2.2.2
  package-lock.json
  package.json
Labels: snyk, security

#92 [Snyk] Upgrade react-router-dom from 7.4.0 to 7.5.1
  package-lock.json
  package.json
Labels: snyk, security
